import type { Metadata } from "next";
import "../styles/globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Booking Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" data-theme="light">
      <body className="w-screen h-full dark:bg-dark-neutral bg-light-neutral">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
